<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2 tabbable tabs-left">
            <ul class="nav nav-tabs" style="width:100%" >
                <li<?=($section == 'home')? ' class="active"': null;?>>
                    <a href="<?=$this->url('hyperion', array('controller' => null))?>">
                        <i class="icon-home"></i>
                        Home
                    </a>
                </li>
                <li<?=($section == 'dns')? ' class="active"': null;?>>
                    <a href="<?=$this->url('hyperion', array('controller' => 'domains'))?>">
                        <i class="icon-th"></i>
                        DNS
                    </a>
                </li>
                <li>
                    <a href="#" onclick="alert('not implemented yet'); return false">
                        <i class="icon-cog"></i>
                        Servers
                    </a>
                </li>
                <li>
                    <a href="#" onclick="alert('not implemented yet'); return false">
                        <i class="icon-file"></i>
                        Files
                    </a>
                </li>
                <li>
                    <a href="#" onclick="alert('not implemented yet'); return false">
                        <i class="icon-random"></i>
                        Load Balancers
                    </a>
                </li>
            </ul>
        </div>
        <div class="span10">
        <?php if (isset($messages) && count($messages)) { ?>
            <div class="alert">
                <a class="close" data-dismiss="alert">×</a>
                <?=$this->htmlList($messages);?>
            </div>
        <?php } ?>
            
            <?=$this->content?>
            
        </div>
    </div>
</div>