<ul class="breadcrumb">
    <li class="active">
        <a href="<?=$this->url('hyperion', array('controller'=>'domains', 'action' => null));?>">Domains</a>
    </li>
</ul>

<h1>Available Domains</h1>
<table class="table table-striped">
    <thead>
        <tr><th>Domain</th><th>Actions</th></tr>
    </thead>
    <tbody>
        <?php foreach ($domains AS $domain) { ?>
        <tr>
            <td><?=$this->escape($domain->name);?></td>
            <td>
                <a href="<?=$this->url('hyperion/query', array('controller'=>'domains', 'action' => 'detail', 'id' => $domain->id));?>" title="View domain Details"><i class="icon-list-alt"></i>Details</a>
            </td>
        </tr>
        <?php } ?>
    </tbody>
    <tfoot><tr><td>&nbsp;</td><td>&nbsp;</td></tr></tfoot>
</table>
