<ul class="breadcrumb">
    <li class="active">
        <a href="<?=$this->url('hyperion', array('controller'=>'domains', 'action' => null));?>">Domains</a>
    </li>
</ul>

<h1>Available Domains</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Domain</th>
            <th>
                <a href="<?=$this->url('hyperion', array('controller'=>'domains', 'action' => 'create'));?>"><i class="icon-plus-sign"></i> Create Domain</a>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($domains AS $domain) { ?>
        <tr>
            <td><?=$this->escape($domain->name);?></td>
            <td>
                <a href="<?=$this->url('hyperion/query', array('controller'=>'domains', 'action' => 'detail', 'id' => $domain->id));?>" title="View Domain Details"><i class="icon-info-sign"></i>Details</a>
                <a href="<?=$this->url('hyperion/query', array('controller'=>'domains', 'action' => 'edit', 'id' => $domain->id));?>" title="Edit Domain"><i class="icon-pencil"></i>Edit</a>
                <a href="<?=$this->url('hyperion/query', array('controller'=>'domains', 'action' => 'delete', 'id' => $domain->id));?>" title="Delete Domain"><i class="icon-trash"></i>Delete</a>
            </td>
        </tr>
        <?php } ?>
    </tbody>
    <tfoot><tr><td colspan="2">&nbsp;</td></tr></tfoot>
</table>
