<ul class="breadcrumb">
    <li>
        <a href="<?=$this->url('hyperion', array('controller'=>'domains', 'action' => null));?>">Domains</a> <span class="divider">/</span>
    </li>
    <li class="active">
        Async Jobs
    </li>
</ul>

<p>From here you can review asyncronous jobs that have been made</p>
<table>
    <thead>
        <tr><th>Job ID</th><th>Status</th></tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
        <tr><td colspan="2"></td></tr>
    </tfoot>
</table>
